---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
    
    - name: Upgrade all flatpaks 📅
      command: flatpak update --noninteractive
      register: flatpak_update_output
      changed_when: "'app/' in flatpak_update_output.stdout"

    - name: Update homebrew packages
      homebrew:
        update_homebrew: true
        upgrade_all: true
      become_user: lkims
      environment:
        PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"
        HOME: "/home/lkims"

  tasks:
    - name: Check if ANSIBLE_FORCE_COLOR setting is set
      debug:
        msg: "{{ lookup('config', 'ANSIBLE_FORCE_COLOR') | bool }}"

  
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/miniconda.yml
    - include_tasks: tasks/desktop_env.yml
    - include_tasks: tasks/change_terminal.yml



    


