# tasks to complete before running roles
- hosts: all
  tags: always
  become: true
  
  tasks:
    - name: Install Zsh
      apt:
        name: zsh
        state: present

    - name: Change default shell to Zsh
      user:
        name: "{{ lkims }}"
        shell: /bin/zsh