---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: add ansible user
      user:
        name: velociraptor
        system: yes

    - name: set up sudo for ansible user
      copy:
        src: files/sudoer_velociraptor
        dest: /etc/sudoers.d/velociraptor
        owner: root
        group: root
        mode: 0440

    - name: Install Zsh
      apt:
        name: zsh
        state: present

    - name: change user shell to zsh 
      user:
        name: lkims
        shell: /bin/zsh

 # New tasks for Homebrew installation
    - name: Install Homebrew dependencies
      apt:
        name:
          - build-essential
          - procps
          - curl
          - file
          - git
          - python3-psutil
        state: present

    - name: Check if homebrew is already installed
      stat:
        path: /home/linuxbrew/.linuxbrew/bin/brew
      register: homebrew_installed

    - name: Ensuer sodoers.d directory exists
      file: 
        path: /etc/sudoers.d
        state: direcoty
        mode: '0755'
      when: not homebrew_installed

    - name: Add NPOASSWD sodu access for Anisble user
      lineinfile:
        path: /etc/soduers.d/ansible-homebrew
        line: "lkims ALL=(ALL) NOPASSWD: ALL"
        create: yes
        validate: 'visodu -cf %s'
        mode: '0440'
      when: not homebrew_installed

    - name: Download Homebrew installation script
      get_url:
        url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
        dest: /tmp/homebrew_install.sh
        mode: '0755'
      become: false
      become_user: lkims
      when: not homebrew_installed

    - name: Run Homebrew installer
      become: no
      become_user: lkims
      shell: /bin/bash /tmp/homebrew_install.sh
      when: not homebrew_installed

    - name: Cleanup Homebrew installation script
      file:
        path: /tmp/homebrew_install.sh
        state: absent
      become: false
      when: not homebrew_installed

    - name: Display homebrew installation status
      debug:
        msg: "Homebrew is already installed"
      when: homebrew_installed

    - name: Display homebrew installation completion message
      debug:
        msg: "Homebrew has been installed"
      when: not homebrew_installed

    - name: Install htop using Homebrew
      homebrew:
        name: 
          - gcc
          - htop
          - ripgrep
          - tlrc
          - bat
          - zoxide
          - fzf
          - zsh-autosuggestions
          - zsh-syntax-highlighting
          - thefuck
          - fastfetch
          - powerlevel10k
        state: present
      become: true
      become_user: lkims
      environment:
        PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"
        HOME: "/home/lkims"

    - name: Copy p10k config
      copy:
        src: "files/p10k.zsh"
        dest: "/home/lkims/.p10k.zsh"
        owner: lkims
        group: lkims
      become: true

    - name: Ensure custom fonts directory exists
      file:
        path: "/usr/local/share/fonts/custom"
        state: directory
        mode: '0755'

    - name: Copy entire fonts directory
      copy:
        src: "files/fonts/"
        dest: "/usr/local/share/fonts/custom/"
        owner: root
        group: root
        mode: '0644'

    - name: Install dconf-cli
      apt:
        name: dconf-cli
        state: present

    - name: Set terminal font
      become: true
      become_user: lkims
      shell: |
        dconf write /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font "'MesloLGS NF 12'"
        dconf write /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-system-font false
      environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus

    - name: copy .zshrc file
      copy:
        src: files/zshrc
        dest: /home/lkims/.zshrc
        owner: lkims
        group: lkims

    - name: set 24h
      become_user: lkims
      dconf:
        key: "/org/gtk/settings/file-chooser/clock-format"
        value: "'24h'"

    - name: set 24h
      become_user: lkims
      dconf:
        key: "/org/gnome/desktop/interface/clock-format"
        value: "'24h'"

    - name: Remove mouse acceleration
      become_user: lkims
      dconf:
        key: "/org/gnome/desktop/peripheral/mouse/accel-profrile"
        value: "'flat'"


    - name: Add Flathub repository
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: system
        state: present

    - name: Install packages using Flatpak
      flatpak:
        name: "{{ item }}"
        state: present
        method: system
      loop:
        - com.brave.Browser
        - com.valvesoftware.Steam
        - com.github.iwalton3.jellyfin-media-player
        - com.discordapp.Discord
        - com.github.tchx84.Flatseal
        - com.heroicgameslauncher.hgl
        - com.mattjakeman.ExtensionManager
        - com.protonvpn.www
        - com.rustdesk.RustDesk
        - com.visualstudio.code
        - dev.deedles.Trayscale
        - io.mpv.Mpv
        - md.obsidian.Obsidian
        - org.filezillaproject.Filezilla
        - org.keepassxc.KeePassXC
        - org.localsend.localsend_app




