---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
    
    - name: Upgrade all flatpaks 📅
      command: flatpak update --noninteractive
      register: flatpak_update_output
      changed_when: "'app/' in flatpak_update_output.stdout"

    - name: Update Homebrew and upgrade all packages
      homebrew:
        update_homebrew: true
        upgrade_all: true

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/miniconda.yml
    - include: tasks/change_terminal.yml
    - include: tasks/desktop_env.yml


    


