---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
        upgrade: dist
        chache_valid_time: 3600

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/miniconda.yml
    - include: tasks/change_terminal.yml
    - include: tasks/desktop_env.yml


    


