- name: Copy p10k config
  copy:
    src: "files/p10k.zsh"
    dest: "/home/lkims/.p10k.zsh"
    owner: lkims
    group: lkims
  become: true

- name: Ensure custom fonts directory exists
  file:
    path: "/usr/local/share/fonts/custom"
    state: directory
    mode: '0755'

- name: Copy entire fonts directory
  copy:
    src: "files/fonts/"
    dest: "/usr/local/share/fonts/custom/"
    owner: root
    group: root
    mode: '0644'
  register: fonts_copy

- name: Update font cache
  ansible.builtin.command: fc-cache -f -v
  when: fonts_copy.changed


- name: set terminal font
  become_user: lkims
  dconf:
    key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font
    value: "'MesloLGS NF 12'"

- name: set terminal font 2
  become_user: lkims
  dconf:
    key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-system-font
    value: "'false'"

- name: Remove mouse acceleration
  become_user: lkims
  dconf:
    key: "/org/gnome/desktop/peripheral/mouse/accel-profrile"
    value: "'flat'"

- name: copy .zshrc file
  copy:
    src: files/zshrc
    dest: /home/lkims/.zshrc
    owner: lkims
    group: lkims
