- name: Install dconf-cli
  apt:
    name: dconf-cli
    state: present

- name: set 24h
  become_user: lkims
  dconf:
    key: "/org/gtk/settings/file-chooser/clock-format"
    value: "'24h'"

- name: set 24h
  become_user: lkims
  dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'24h'"

- name: Remove mouse acceleration
  become_user: lkims
  dconf:
    key: "/org/gnome/desktop/peripheral/mouse/accel-profrile"
    value: "'flat'"
