- name: add ansible user
  user:
    name: velociraptor
    system: yes

- name: set up sudo for ansible user
  copy:
    src: files/sudoer_velociraptor
    dest: /etc/sudoers.d/velociraptor
    owner: root
    group: root
    mode: 0440

- name: set up sodu path for brew applications
  copy:
    src: files/sudoer_lkims
    dest: /etc/sudoers.d/lkims
    owner: root
    group: root
    mode: 0440
